name: Deploy API to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 20.106.193.95 >> ~/.ssh/known_hosts

      - name: Clean remote directory
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.106.193.95 << 'EOF'
            which pm2 || npm install -g pm2
            pm2 delete all || true
            mkdir -p ~/backend-api
            sudo rm -rf ~/backend-api/*
          EOF

      - name: Copy files to VM
        run: |
          scp -r . azureuser@20.106.193.95:~/backend-api/

      - name: Install dependencies and start app
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.106.193.95 << 'EOF'
            cd ~/backend-api
            npm install
            npm run build
            pm2 start npm --name backend-api -- run start
          EOF
