name: Deploy API to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 3.110.218.166 >> ~/.ssh/known_hosts

      - name: Prepare EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.110.218.166 << 'EOF'
            # Update & install curl
            sudo apt-get update
            sudo apt-get install -y curl

            # Install Node.js & npm (Node 18 LTS)
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Install PM2 if not already
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Prepare app directory
            pm2 delete all || true
            mkdir -p ~/backend-api
            rm -rf ~/backend-api/*
          EOF

      - name: Copy files to EC2 (excluding .git)
        run: |
          rsync -av --exclude='.git' . ubuntu@3.110.218.166:~/backend-api/

      - name: Install dependencies & start app
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.110.218.166 << 'EOF'
            cd ~/backend-api
            npm install
            npm run build || true   # in case you don't have a build script
            pm2 start server.js --name backend-api
          EOF
